language: node_js
node_js:
  - '10'
cache:
  yarn: true
  directories:
    - node_modules
dist: trusty

before_script:
  - yarn

script:
  - yarn lint
  - yarn build

notifications:
  slack:
    rooms:
      secure: JhcqfboOJcR/MhuSDEMRaIXjMi5TGTsM3FKVimcdwVp8+5xVlyDdP17qZZAjrxe2LJQ4kuOFALunX4hdam0bg01EnqWsCqyEbtYUD30sDujRd58boVPBAvBxXIlt/7cZpOv5uIDzi8wf913OakDw7H8q8CIxskIi6mQqqQgfl51abQZ/5Tn4l0f37wPr6zUVr46eylCJ3LiHBqVm1QBRAedQJGRy3BooAOD6nrH25mJAX5e1EFc/l12y2NxstMQv70LWsdN9SKxTlBKR6AJVjEi4NQEst665qMJMLej3TaTFyKSfnb5s3nZmDTblImYvVg/JaLb29iV5KV+8iSDA6Xufvd6TXRg42Ju0zJoUnSG3lPnBgqDzVcB1sasEa3mwZhGtCWIYi7mxRM1Ue9Tg9Y3gS/fH9KbC0bP+OI7ucUTGePEtIMyahdm51nU4caA0/yu847Wm/k1zR/biB+sSEZNkkieAg53amH49TXvOaSuMaD6JqskxqBiUUKC6xO0WAsITFQfJ8W5eIapNy9aFLwkIupQUyHmrRGe4fQM5wZw+u6w8VdQplYlklv04auFtO0TnEWNMonWRbyXLYk/XIk2qVGcdrE3/jyPOVUPyKIk2hgSpVfXTbakOdjyh3pJ1k9+gdbKRQfX+Ie4jHWKhyoWcFa/B5Fp094GZbPsp4Bg=
